// flow-typed signature: 29e53878971afd361b6917ff2bb40f32
// flow-typed version: <<STUB>>/gulp-tap_v^2.0.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-tap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-tap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-tap/lib/tap' {
  declare module.exports: any;
}

declare module 'gulp-tap/tests/fixtures/js' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-tap/index' {
  declare module.exports: $Exports<'gulp-tap'>;
}
declare module 'gulp-tap/index.js' {
  declare module.exports: $Exports<'gulp-tap'>;
}
declare module 'gulp-tap/lib/tap.js' {
  declare module.exports: $Exports<'gulp-tap/lib/tap'>;
}
declare module 'gulp-tap/tests/fixtures/js.js' {
  declare module.exports: $Exports<'gulp-tap/tests/fixtures/js'>;
}
