// flow-typed signature: ff2ff98843634731b3fd7602f0fa0fe6
// flow-typed version: <<STUB>>/next-transpile-modules_v^2.3.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-transpile-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-transpile-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-transpile-modules/index' {
  declare module.exports: $Exports<'next-transpile-modules'>;
}
declare module 'next-transpile-modules/index.js' {
  declare module.exports: $Exports<'next-transpile-modules'>;
}
