// flow-typed signature: a3f9840d80a150e0c78cb9581d0be8e4
// flow-typed version: <<STUB>>/parse-gitignore_v^1.0.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-gitignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-gitignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-gitignore/index' {
  declare module.exports: $Exports<'parse-gitignore'>;
}
declare module 'parse-gitignore/index.js' {
  declare module.exports: $Exports<'parse-gitignore'>;
}
