// flow-typed signature: 898c38f83f92309399815b1ed010a2f6
// flow-typed version: <<STUB>>/replace-in-file_v^5.0.2/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'replace-in-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'replace-in-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'replace-in-file/bin/cli' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/combine-config' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/error-handler' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/get-paths-async' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/get-paths-sync' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/glob-async' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/load-config' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/make-replacements' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/parse-config' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/replace-async' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/replace-sync' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/helpers/success-handler' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/replace-in-file' {
  declare module.exports: any;
}

declare module 'replace-in-file/lib/replace-in-file.spec' {
  declare module.exports: any;
}

declare module 'replace-in-file/test/helpers/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'replace-in-file/bin/cli.js' {
  declare module.exports: $Exports<'replace-in-file/bin/cli'>;
}
declare module 'replace-in-file/index' {
  declare module.exports: $Exports<'replace-in-file'>;
}
declare module 'replace-in-file/index.js' {
  declare module.exports: $Exports<'replace-in-file'>;
}
declare module 'replace-in-file/lib/helpers/combine-config.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/combine-config'>;
}
declare module 'replace-in-file/lib/helpers/error-handler.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/error-handler'>;
}
declare module 'replace-in-file/lib/helpers/get-paths-async.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/get-paths-async'>;
}
declare module 'replace-in-file/lib/helpers/get-paths-sync.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/get-paths-sync'>;
}
declare module 'replace-in-file/lib/helpers/glob-async.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/glob-async'>;
}
declare module 'replace-in-file/lib/helpers/load-config.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/load-config'>;
}
declare module 'replace-in-file/lib/helpers/make-replacements.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/make-replacements'>;
}
declare module 'replace-in-file/lib/helpers/parse-config.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/parse-config'>;
}
declare module 'replace-in-file/lib/helpers/replace-async.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/replace-async'>;
}
declare module 'replace-in-file/lib/helpers/replace-sync.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/replace-sync'>;
}
declare module 'replace-in-file/lib/helpers/success-handler.js' {
  declare module.exports: $Exports<'replace-in-file/lib/helpers/success-handler'>;
}
declare module 'replace-in-file/lib/replace-in-file.js' {
  declare module.exports: $Exports<'replace-in-file/lib/replace-in-file'>;
}
declare module 'replace-in-file/lib/replace-in-file.spec.js' {
  declare module.exports: $Exports<'replace-in-file/lib/replace-in-file.spec'>;
}
declare module 'replace-in-file/test/helpers/setup.js' {
  declare module.exports: $Exports<'replace-in-file/test/helpers/setup'>;
}
