// flow-typed signature: 9475306b873905f56a79cb38cc0e69db
// flow-typed version: <<STUB>>/version-bump-prompt_v^5.0.6/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'version-bump-prompt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'version-bump-prompt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'version-bump-prompt/bin/bump' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/cli/exit-code' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/cli/help' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/cli' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/cli/parse-args' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/fs' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/get-new-version' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/get-old-version' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/git' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/manifest' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/normalize-options' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/operation' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/release-type' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/run-npm-script' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/types/version-bump-options' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/types/version-bump-progress' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/types/version-bump-results' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/update-files' {
  declare module.exports: any;
}

declare module 'version-bump-prompt/lib/version-bump' {
  declare module.exports: any;
}

// Filename aliases
declare module 'version-bump-prompt/bin/bump.js' {
  declare module.exports: $Exports<'version-bump-prompt/bin/bump'>;
}
declare module 'version-bump-prompt/lib/cli/exit-code.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/cli/exit-code'>;
}
declare module 'version-bump-prompt/lib/cli/help.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/cli/help'>;
}
declare module 'version-bump-prompt/lib/cli/index' {
  declare module.exports: $Exports<'version-bump-prompt/lib/cli'>;
}
declare module 'version-bump-prompt/lib/cli/index.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/cli'>;
}
declare module 'version-bump-prompt/lib/cli/parse-args.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/cli/parse-args'>;
}
declare module 'version-bump-prompt/lib/fs.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/fs'>;
}
declare module 'version-bump-prompt/lib/get-new-version.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/get-new-version'>;
}
declare module 'version-bump-prompt/lib/get-old-version.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/get-old-version'>;
}
declare module 'version-bump-prompt/lib/git.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/git'>;
}
declare module 'version-bump-prompt/lib/index' {
  declare module.exports: $Exports<'version-bump-prompt/lib'>;
}
declare module 'version-bump-prompt/lib/index.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib'>;
}
declare module 'version-bump-prompt/lib/manifest.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/manifest'>;
}
declare module 'version-bump-prompt/lib/normalize-options.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/normalize-options'>;
}
declare module 'version-bump-prompt/lib/operation.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/operation'>;
}
declare module 'version-bump-prompt/lib/release-type.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/release-type'>;
}
declare module 'version-bump-prompt/lib/run-npm-script.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/run-npm-script'>;
}
declare module 'version-bump-prompt/lib/types/version-bump-options.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/types/version-bump-options'>;
}
declare module 'version-bump-prompt/lib/types/version-bump-progress.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/types/version-bump-progress'>;
}
declare module 'version-bump-prompt/lib/types/version-bump-results.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/types/version-bump-results'>;
}
declare module 'version-bump-prompt/lib/update-files.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/update-files'>;
}
declare module 'version-bump-prompt/lib/version-bump.js' {
  declare module.exports: $Exports<'version-bump-prompt/lib/version-bump'>;
}
